# Generated by Django 3.2.15 on 2023-02-04 16:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course_api', '0002_enroll_favorite'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='enroll',
            unique_together={('course', 'user')},
        ),
        migrations.AlterUniqueTogether(
            name='favorite',
            unique_together={('course', 'user')},
        ),
    ]
